### ISSUE TITLE
Doc update missing?

### ISSUE THREAD

**Issue by nick-zh** [arnaud-lb/php-rdkafka-doc#7]
Dear @arnaud-lb 

I wanted to update the doc and searched for all the open doc issues in the main repo,
i stumbled across this:
https://github.com/arnaud-lb/php-rdkafka/issues/68
I see that in the current [webpage](https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.examples-producer.html) there is a block with the poll:
```
while ($rk->getOutQLen() > 0) {
    $rk->poll(50);
}
```
I cloned this repo, but i was unable to find it, i asssumed it was here: php-rdkafka-doc/en/reference/rdkafka/examples/producer.xml

Cheers,
Nick

**Comment by arnaud-lb** [comment]
Will spotted, some commit had not been pushed. This is fixed now.
